### ISSUE TITLE
Handle missing settings.yaml files

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/tarbell#13]
Attempting to run the Tarbell admin server with no `.tarbell` folder results in:

```
File "/Users/hbillings/KnightLab/Repos/tarbell-kl/tarbell/cli.py", line 422, in tarbell_admin
    admin_site = TarbellAdminSite(settings)
File "/Users/hbillings/KnightLab/Repos/tarbell-kl/tarbell/admin.py", line 36, in __init__
    self.credentials = json.loads(api.credentials.to_json())
AttributeError: 'NoneType' object has no attribute 'credentials'
```

Attempting to run the server with a `.tarbell` folder but no `settings.yaml`fires the following TypeError:

```
File "/Users/hbillings/KnightLab/Repos/tarbell-kl/tarbell/admin.py", line 91, in main
    project_list = list_projects(self.settings.config.get('projects_path'))
File "/Users/hbillings/KnightLab/Repos/tarbell-kl/tarbell/admin_utils.py", line 154, in list_projects
    for directory in os.listdir(projects_dir):
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by jywsn** [comment]
Running the server with a .tarbell folder but no settings.yaml starts up with configuration modal sequence for me.

**Comment by jywsn** [comment]
Attempting to run the Tarbell admin server with no .tarbell folder also starts up the configuration modal sequence for me.  Please verify.  If you're still getting the error, then I'd like to look at your setup in person.

**Comment by hbillings** [comment]
Derp derp.
