### ISSUE TITLE
Tilde expansion broken if run from a folder other than where Tarbell is installed

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/tarbell#14]
When the `projects_dir` value is something like `~/Projects/tarbell`, the tilde should be automatically expanded to the full path. Otherwise, visiting the tarbell admin page returns an OS path error if `tarbell admin` is run outside Tarbell's install location.

**Comment by jywsn** [comment]
409689dfd063db6b25ed69abee0f55c7605e6d61
