### ISSUE TITLE
Chrome blocks config modal without warning

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/tarbell#16]
The config modal works fine in FF, Safari. But Chrome needs popups to be enabled, and doesn't offer the usual "Popup blocked. Allow popups for this site?" prompt. Not sure if there's a way to trigger that warning, or to otherwise display a message asking the user to allow popups.

**Comment by jywsn** [comment]
Under Settings > Content Settings, I have "Do not allow any site to show pop-ups" selected. And Chrome is not blocking my config modal.  I wouldn't know how to get Chrome to block the modal.  It's not really a pop-up, is it?  I thought a a pop-up was a separate window.  ?

**Comment by hbillings** [comment]
I had to change my Content Settings to "Allow all sites to show pop-ups," but now that I've changed it back to "Do not allow," the modal still works. So...I'll keep an eye on this myself, but maybe it's just a weird phantom symptom.
