### ISSUE TITLE
If client_secrets already exists, trying to select it again errors (screenshot)

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/tarbell#18]
My client_secrets was already loaded, but I clicked "select secrets file" anyway, chose the same client_secrets file that I'd previously chosen, and got this error (from line 9 of admin-util.js): 
![screen shot 2015-04-27 at 12 56 47 pm](https://cloud.githubusercontent.com/assets/509309/7353928/ff2b5bf6-ecdc-11e4-8cea-c2e1944eee50.png)

**Comment by jywsn** [comment]
Conflict between "backup" parameter and "backup" function.

Fixed a51dc952fcf393a63e81ddea5e6ebdfe162c1231
