### ISSUE TITLE
delete blueprint & project management code

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/tarbell#24]
Let's plan to roll the settings config and the `tarbell admin` command out first. I don't know if it makes sense to create a new branch for the settings and delete all of the blueprint/project code from it, or if we just want to hide the tabs for blueprints/projects on the admin.

**Comment by jywsn** [comment]
aafde52fd4d27ef1ad28fe1c23f8abe5ebb46d74
a921ed642ea67684fd63e2ffbe1993d1f3b960c8

**Comment by jywsn** [comment]
Gaah, not done.  Re-opening.

**Comment by jywsn** [comment]
No... this is done.  I don't know WTF I was just looking at.
